del "*.sdf"

del "bin\Debug\*.obj"
del "bin\Debug\*.pch"
del "bin\Debug\*.ilk"
del "bin\Debug\*.sbr"
del "bin\Debug\*.idb"
del "bin\Debug\*.pdb"
del "bin\Debug\*.bsc"
del "bin\Debug\*.res"
del "bin\Debug\*.exp"
del "bin\Debug\*.lib"
del "bin\Debug\*.exe"
rem del "bin\Debug\*.dll"
del "bin\Debug\*.cnt"
del "bin\Debug\*.GID"
del "bin\Debug\*.hlp"
del "bin\Debug\*.dep"
del "bin\Debug\*.htm"
del "bin\Debug\*.manifest"
del "bin\Debug\*.tlog"
del "bin\Debug\*.log"
del "bin\Debug\*.rc"
del "bin\Debug\*.lastbuildstate"

del "bin\Release\*.obj"
del "bin\Release\*.pch"
del "bin\Release\*.ilk"
del "bin\Release\*.sbr"
del "bin\Release\*.idb"
del "bin\Release\*.pdb"
del "bin\Release\*.bsc"
del "bin\Release\*.res"
del "bin\Release\*.exp"
del "bin\Release\*.lib"
rem del "bin\Release\*.exe"
rem del "bin\Release\*.dll"
del "bin\Release\*.cnt"
del "bin\Release\*.GID"
del "bin\Release\*.hlp"
del "bin\Release\*.dep"
del "bin\Release\*.htm"
del "bin\Release\*.manifest"
del "bin\Release\*.tlog"
del "bin\Release\*.log"
del "bin\Release\*.rc"
del "bin\Release\*.lastbuildstate"

rmdir /s /q obj\Debug
rmdir /s /q obj\Release